FROM texlive/texlive:latest AS builder

WORKDIR /app

COPY my_resume.tex ./
COPY sections/ ./sections/
COPY packages.txt ./
COPY res.cls ./

RUN tlmgr update --self \
 && tlmgr install $(cat packages.txt | xargs) biber \
 && tlmgr path add \
 && latexmk -pdf -interaction=nonstopmode my_resume.tex