name: Build Resume PDF and Docker Image

on:
  push:
    branches:
      - main

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write # Needed to push to GitHub Container Registry

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install TinyTeX
        run: |
          wget -qO- "https://yihui.org/tinytex/install-bin-unix.sh" | sh -s -- --scheme=basic
          export PATH=$HOME/.TinyTeX/bin/x86_64-linux:$PATH
          tlmgr update --self
          tlmgr install $(cat packages.txt | tr '\n' ' ') biber
      - name: Add TinyTeX to PATH
        run: |
          echo "PATH=$HOME/.TinyTeX/bin/x86_64-linux:$PATH" >> $GITHUB_ENV

      - name: Compile LaTeX to PDF
        run: |
          # The TinyTeX action should add TeX Live binaries to the PATH
          # Attempting up to 3 times for latexmk to resolve references
          latexmk -pdf -interaction=nonstopmode my_resume.tex
          latexmk -pdf -interaction=nonstopmode my_resume.tex
          latexmk -pdf -interaction=nonstopmode my_resume.tex


      - name: Upload PDF artifact
        uses: actions/upload-artifact@v4
        with:
          name: resume-pdf
          path: my_resume.pdf

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: christophersherman
          password: ${{ secrets.GHCR_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          platforms: |
            linux/amd64
            linux/arm64
          push: true
          tags: ghcr.io/christophersherman/myresume:latest
